/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./www/index.html', './www/js/**/*.js'],
  theme: {
    extend: {
      colors: {
        'on-primary': '#ffffff',
        'surface-container-low': '#f2f4f2',
        'primary-fixed': '#79f7e6',
        'secondary-container': '#cae5e0',
        'on-secondary-fixed': '#061f1d',
        'tertiary-fixed-dim': '#abcae5',
        'surface-variant': '#e1e3e1',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8eadc7',
        'on-tertiary-fixed-variant': '#2b4a60',
        'surface-bright': '#f8faf8',
        'surface-tint': '#006a61',
        'surface-container-high': '#e6e9e7',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#4e6763',
        'secondary-fixed': '#cde8e3',
        'on-surface-variant': '#3c4947',
        'on-tertiary-fixed': '#001e2f',
        error: '#ba1a1a',
        secondary: '#4a635f',
        surface: '#f8faf8',
        'on-tertiary-container': '#224157',
        'on-primary-fixed': '#00201c',
        'inverse-on-surface': '#eff1ef',
        'on-background': '#191c1b',
        'inverse-primary': '#59daca',
        'on-primary-container': '#004640',
        'error-container': '#ffdad6',
        'on-primary-fixed-variant': '#005049',
        'surface-dim': '#d8dad9',
        primary: '#006a61',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#b1ccc7',
        'tertiary-fixed': '#cae6ff',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#32bcad',
        'on-error-container': '#93000a',
        'surface-container': '#eceeec',
        'inverse-surface': '#2e3130',
        'on-secondary-fixed-variant': '#334b48',
        'on-surface': '#191c1b',
        'primary-fixed-dim': '#59daca',
        background: '#f8faf8',
        'surface-container-highest': '#e1e3e1',
        tertiary: '#446279',
        outline: '#6c7a77',
        'outline-variant': '#bbc9c6',
        'badge-cpf-bg': '#e3edfd',
        'badge-cpf-text': '#1a4fa8',
        'badge-cnpj-bg': '#f0e6fa',
        'badge-cnpj-text': '#6a2fb5',
        'badge-email-bg': '#e1f5e6',
        'badge-email-text': '#1c7a3a',
        'badge-telefone-bg': '#fdeadd',
        'badge-telefone-text': '#b45a10',
        'badge-aleatoria-bg': '#e9eaea',
        'badge-aleatoria-text': '#54605e',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
        '2xl': '1rem',
        '3xl': '1.5rem',
      },
      spacing: {
        gutter: '16px',
        base: '8px',
        'margin-tablet': '24px',
        'stack-lg': '24px',
        'stack-md': '12px',
        'stack-sm': '4px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['57px', { lineHeight: '64px', letterSpacing: '-0.25px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0.25px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1px', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0.5px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.5px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '0px', fontWeight: '600' }],
        'title-lg': ['22px', { lineHeight: '28px', letterSpacing: '0px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0px', fontWeight: '600' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
